spring:
  config :
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true

imgbb:
  api:
    key: ${IMGBB_KEY}


dropbox:
  access-token: ${DROP_BOX_ACCESS_TOKEN}
  client-identifier: project-catalog/1.0

openrouter:
  api:
    url: https://openrouter.ai/api/v1/chat/completions
    key: ${OPEN_ROUTER_API}
# Commenting out proxy configuration that might interfere with external API calls
# http:
#   proxyHost: localhost
#   proxyPort: 51182