spring:
  datasource:
    url: jdbc:postgresql://ep-twilight-truth-a1n117t8-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_lAFvunkQH60M
  jpa:
    show-sql: true

imgbb:
  api:
    key: 3ae4bcda8db1a224fb4bbb4db75386c2

mega:
  email: heinminthant259@gmail.com
  password: Phyothirikyaw@25
  upload-directory: /ucsmg

dropbox:
  access-token: "sl.u.AF4W1wjQRmrSoYn5blxsFplVrIOK6DOXIKVxVCW-ancT1U65J4IGqmvl08sCMIl_LU5ZuvhjAyKwjuytSJf2muGOMRk7arLr6JFBsDSckmJi_Yz68pGO6ScfBzhLk4XNbHCV6w481hk_NLkKTpDNfsJKXqqPz1MXd8Sp5OtWSTv8womFIxxLjKSpoSjxMQd1mZetxZ1ENK02aPf2DDRy6E_iWBOsEZw7mnCspbtTZDnfWC1L5y3_KpcdcBkoFIY-Ti405NYM2AmFbS0KfuRJE9vccUPsVJbgn5PnKPbZjFBTQkojHb3FQGm4oB_CORH-t_dDKE3qbtK8RAUrTWMCa65SallIXE_ZpWjr9Een1TW2jms4LjKYa2I1wCBELu5hH4vl91vPrJHMr0SLu4RQtLWEtV_lX9gGZbXvE1PLKFJBgsuH_TyeXUUTBaFtjdFqp8lLFFGYOuyXuMJTh5RpocACg4oA2Un21I0yOVCw3ZnmWJfADn8ZwSysSbQOzA-a-VXvg4ebrnYwZK8CwPdi7Vdt_ZTobq0BX9ANsnHDR2qFsLdwbCuouc3CmMsk16evlSvXtz76cc2KNP4MW1-i59V-uq7x5IURAU64ASe0GCiKlzmwIKkAFwmiHcu8GUB_n6aTOk0Uf-lbdRVFpwtZFo_f-I9TfT1L6TcipaJorxj4-0WCWSdx9UGFD9lxAw_JNgdS13pfMTe1ZYaeMmk0iyYwBNWAV00F7iSNv_FZSs_BOKbHyxg0Fl6-v41TQFBXtR-KnGFL9I_sKtPL0oUUrWrm95taSoidVx4n_5GnP0UEzQ7Rlh6Ih-OAb3FDDhSEIHBMxjIcRQDAl2wDEQpfstBH-yoTwyW4W9HLc5j8-thrZdq2kqdOqH-LteCCqHZgj4Ho0bruyMan-4-QTSa_MbgvTaqs5445nkp-6n5kz6knp0exBWhleRZj5zNzhN7AtR7hJJht7IlqLHU3LvBsKXZvTFa4Owdw6bdQ3BFwNym0vJVD1Ib0J9AfSeZFEiK9hFVvQbizXzju5Dv5BXaePyLRrgZPQug4mFxvzoZvcx42JLVDutDQ3IXqc_qnbWe7w3kZZ0F1wJWRiidpuCkwzIrcztNkEYty01noHcDXuqzEU2BJkLCQ61QfrSutPeFv-HXjyKWHytUp9BboYhB8fSPthW0NFvhlSKLjz7qRpbBWbOji5uULnYitINROD7X9vb3AkxZafXq_zYi81ZqQgiIWZQO369bHfjjVeHBDbsunTxwin663q2N755X8i_6_Z033OWetj1F25AlcrFm1Odw-9FqY8pruZ1fSisuZF9MAMtiSqfDlE4aXpSEtb4EBLqaelQyK1sA-85xbbDWAlmDPDJ-c5uFIDcU0gitiucAMzV-F2ChW3ga_T2hbNZft_y2vPJQKg-P-rQZfFr-P7D5WBnTPWYdPz0S96ACP8LKA1g"
  client-identifier: project-catalog/1.0


