spring:
  config :
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

imgbb:
  api:
    key: ${IMGBB_KEY}


dropbox:
  access-token: ${DROP_BOX_ACCESS_TOKEN}
  client-identifier: project-catalog/1.0

openrouter:
  api:
    url: https://openrouter.ai/api/v1/chat/completions
    key: ${OPEN_ROUTER_API}


frontend:
  url: ${FRONTEND_URL}